# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='snack',
        ),
        migrations.AddField(
            model_name='snack',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
