# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_auto_20180425_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='picture_url',
            field=models.CharField(default='http://www.howtobeadad.com/wp-content/uploads/2016/03/vomit-target-chart.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
